name: Release package

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.target }}
    - name: Install wheel
      run: pip3 install wheel setuptools build
    - name: Compile package
      run: python3 -m build --wheel
    - name: Upload sdist
      uses: actions/upload-artifact@v4
      with:
        name: wheels
        path: dist
  upload:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: wheels
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: "*.whl"
