name: Release package

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install wheel
      run: pip3 install wheel
    - name: Compile package
      run: python setup.py bdist_wheel
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*.whl
